version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"  # This stays the same, unless you want to change the app port
    environment:
      - DB_USER=root
      - DB_PASSWORD=password
      - DB_NAME=testdb
      - DB_HOST=db
      - DB_PORT=3307  # Update this to the new port you mapped for MySQL (3307)
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: testdb
    ports:
      - "3307:3306"  # Change the host port to 3307 (the container still uses 3306)
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
